client homelab_network {
    ipaddr = 192.168.8.0/24  # Pozwól wszystkim z Twojej sieci pytać Radiusa
    secret = Inzynierka2026_Secret
}
client tplink-ap {
    ipaddr = 192.168.8.2
    secret = Inzynierka2026_Secret
    shortname = tplink
}

client localhost {
    ipaddr = 127.0.0.1
    secret = testing123
}
