services:
  radius:
    build: .
    container_name: freeradius-server
    restart: unless-stopped
    volumes:
      - ./config/clients.conf:/etc/freeradius/3.0/clients.conf:ro
      - ./config/mods-available/ldap:/etc/freeradius/3.0/mods-enabled/ldap:ro
      - ./config/mods-available/eap:/etc/freeradius/3.0/mods-enabled/eap:ro
      - ./config/sites-available/default:/etc/freeradius/3.0/sites-enabled/default:ro
      - ./config/sites-available/inner-tunnel:/etc/freeradius/3.0/sites-enabled/inner-tunnel:ro
    networks:
      macvlan_net:
        ipv4_address: 192.168.8.201

networks:
  macvlan_net:
    external: true
    name: homelab_macvlan
