
services:
  mysql:
    image: mariadb:10.5
    container_name: zbx-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - zabbix-db:/var/lib/mysql
    restart: unless-stopped
    networks:
      zabbix-network:
        ipv4_address: 172.16.10.2

  zabbix-server:
    image: zabbix/zabbix-server-mysql:ubuntu-7.0-latest
    container_name: zbx-server
    environment:
      DB_SERVER_HOST: mysql
      MYSQL_DATABASE: zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    depends_on:
      - mysql
    ports:
      - "10051:10051"
    restart: unless-stopped
    networks:
      zabbix-network:
        ipv4_address: 172.16.10.3

  zabbix-web:
    image: zabbix/zabbix-web-nginx-mysql:ubuntu-7.0-latest
    container_name: zbx-web
    environment:
      DB_SERVER_HOST: mysql
      MYSQL_DATABASE: zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      ZBX_SERVER_HOST: zabbix-server
      PHP_TZ: Europe/Warsaw
    ports:
      - "8080:8080"
    depends_on:
      - zabbix-server
    restart: unless-stopped
    networks:
      zabbix-network:
        ipv4_address: 172.16.10.4

  zabbix-agent:
    image: zabbix/zabbix-agent:ubuntu-7.0-latest
    container_name: zbx-agent
    environment:
      ZBX_SERVER_HOST: zabbix-server
      ZBX_HOSTNAME: Docker-Agent-1
      ZBX_PASSIVESERVERS: 172.16.10.3
    depends_on:
      - zabbix-server
    restart: unless-stopped
    networks:
      zabbix-network:
        ipv4_address: 172.16.10.5

volumes:
  zabbix-db:
    external: true
    name: zabbix_zabbix-db

networks:
  zabbix-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.10.0/24
