services:
  samba-ad:
    image: instantlinux/samba-dc:latest
    container_name: local-ad-controller
    hostname: dc1
    cap_add:
      - SYS_ADMIN
    environment:
      - DOMAIN_ACTION=provision
      - REALM=homelab.local
      - DOMAIN=HOMELAB
      - ADMIN_PASSWORD_SECRET=admin_password
    volumes:
      - /home/pi/Git/RPi5-Homelab/infrastructure/data:/var/lib/samba
      - /home/pi/Git/RPi5-Homelab/infrastructure/config:/etc/samba
      - /home/pi/Git/RPi5-Homelab/infrastructure/secrets/admin_password:/run/secrets/admin_password:ro
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    restart: always
    networks:
      macvlan_samba:
        ipv4_address: 192.168.8.200

  radius:
    image: freeradius/freeradius-server:latest
    container_name: freeradius-server
    restart: always
    volumes:
      - /home/pi/Git/RPi5-Homelab/infrastructure/config/radius/clients.conf:/etc/raddb/clients.conf:ro
      - /home/pi/Git/RPi5-Homelab/infrastructure/data:/var/lib/samba
    networks:
      macvlan_samba:
        ipv4_address: 192.168.8.201
    depends_on:
      - samba-ad

networks:
  macvlan_samba:
    driver: macvlan
    driver_opts:
      parent: eth0
    ipam:
      config:
        - subnet: 192.168.8.0/24
          gateway: 192.168.8.1
          ip_range: 192.168.8.200/31
